### ISSUE TITLE
Chat and Lobby

### ISSUE THREAD

**Issue by RuyiLi** [crude-cards/protocols#12]
- "Roles" in chat (white for unverified, lime green red for verified, and some other colors for moderators)
- Some chat commands that let you check others' profiles and such (and/or meme commands like Discord's /tableflip)
- Block list
- Filter characters like this (﷽) that could potentially flood channels due to the 1,000 character limit
- Official / Unofficial chat channels. An example of an official channel would be something like "announcements", while an unofficial one would be one created by a user called "bob's squad". Each user can only create one channel.

**Comment by amishshah** [comment]
Most of these seem very overkill for Crude Cards at the moment, and for the sake of simplicity most will not be included in the v1 protocol. However, I am interested in implementing:

1. Client-side commands, e.g. `/tableflip`
2. Message restrictions, e.g. mentioned ﷽

**Comment by amishshah** [comment]
Chat has been implemented.
