### ISSUE TITLE
Centralisation?

### ISSUE THREAD

**Issue by amishshah** [crude-cards/protocols#9]
Should Crude Cards have a centralised server for authentication and storing statistics? This would mean players can see their statistics across servers and possibly make it easier for them to switch servers to join friends. However, it makes all servers dependent on a server that may go down often.

**Comment by Tvde1** [comment]
Yes

**Comment by RuyiLi** [comment]
Should probably provide a reason @Tvde1

**Comment by amishshah** [comment]
Current thoughts are to go _against_ centralisation:

1. Avoids the issue of what to do if the central authentication server goes down (no servers would be affected by outage)
2. Prevents fake data being collected by dummy servers/users that could start to use up a lot of space

**Comment by amishshah** [comment]
Don't believe this is going to happen, will reopen if it there are new points to be made about it.

**Comment by MythicManiac** [comment]
One option (though has it's own issues and is rather complex) is to use Ethereum as a decentralized database and signature based authentication (could also be stored to Ethereum with strong passwords). Implemented properly this would mean you can authenticate users and store their data without a central server or user inconvenience at all.
